### ISSUE TITLE
cannot dlopen libjasper.so

### ISSUE THREAD

**Issue by lal12** [node-3d/image-raub#3]
When installing `3d-core-raub` and using the example from the README I get the following error:
```
internal/modules/cjs/loader.js:800
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: libjasper.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:800:18)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous>(*******/node_modules/image-raub/core.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
```

Any idea on this? Do I have install some local dep? I assumed all are included in a dependency.

**Comment by raub** [comment]
Hello. Could you please specify the OS version? I guess this is the thing missing: https://packages.debian.org/hu/jessie/libjasper1 

Anyway, try to reinstall the modules and see if anything changes, as I added the lib in question to the bundle. May be you will have some other missing lib issues.

See also: https://github.com/node-3d/deps-freeimage-raub/releases/tag/v2.0.0 this is where the bundle is stored. I've just added `libjasper.so.1` from the debian link above. Hope this helps.

**Comment by lal12** [comment]
Sorry I was a little short with information, I wanted to check first whether it is intended to have all dependencies deployed via npm or if local dependencies are needed.

I am on Ubuntu 19.04, as far as I found out yet libjasper is not available for Ubuntu, I didn't looked too deeply into it though. 

I've installed deps-freeimage-raub via npm, shouldn't it be in there?

**Comment by raub** [comment]
Yes, you are right, it is intended to have all the dependencies installed via NPM. However, the dependencies are added per report.

You have to reinstall the node_modules to fetch the new binaries. Just run `npm ci`/`npm i` in your project directory again. Then try to run it as you did the first time.

At least it works in TravisCI on Ubuntu Xenial: https://travis-ci.com/github/node-3d/image-raub/jobs/272670334

**Comment by raub** [comment]
@lal12 I assume the problem is solved. If not, feel free to open this issue back again with any additional info.
